### ISSUE TITLE
treat toots with mentions in them better

### ISSUE THREAD

**Issue by Lana-chan** [theZacAttacks/TwitPoster#11]
current behaviour:
a reply to myself in which i mention any account gets crossposted with that mention removed
example:
https://twitter.com/maplesbian/status/1125751918222106625

expected behaviour:
no change to current behaviour if the mention is my own account
replace mention with account URL if the mention is a different account
example:
"and yes we will be selling them, there's about 100 of them to go, i just gotta figure out some logistics first :3 follow https://computerfairi.es/@transbian bc it'll be announced there"

**Comment by Lana-chan** [comment]
cases in which a toot with a mention other than your own account should be crossposted:
* thread starter (no in_reply_to id)
* toot which reply is to yourself && in_reply_to id has twitter counterpart

that way reply threads spawning from someone else's reply on mastodon do not get crossposted, but if you're self-threading and mention someone else at any point in the thread, it gets crossposted with the url replaced in

**Comment by Lana-chan** [comment]
on second thought for the second case, only checking if in_reply_to id has twitter counterpart should be enough to cover it

**Comment by compufox** [comment]
this should be a fairly easy fix. there's a line that strips out all mentions right before it posts, this can be changed to replace the mention with a link to the account's main page.

**Comment by Lana-chan** [comment]
i think this is still not happening? none of my posts mentioning another user that weren't replies crossed over

**Comment by Lana-chan** [comment]
(im in bed so I'll try this better tomorrow)

**Comment by compufox** [comment]
hmmmmmm
I'll look into this when i get off work.

sorry :/

**Comment by Lana-chan** [comment]
no it's ok!!! there's no rush or worry i just wanted to note this so i
wouldn't forget

**Comment by compufox** [comment]
This should be fixed now. I added in a config option, so be sure to check that out! :3
