### ISSUE TITLE
implement persistent list of equivalent ids to improve threading

### ISSUE THREAD

**Issue by Lana-chan** [theZacAttacks/TwitPoster#2]
currently the script only stores the last tweet's and last toot's ids and in a volatile variable

this suggestions proposes two things:
- store every id generated instead of only the last one (possibly culling them after a period of time to avoid bloat)
- store them outside the script (file, sqlite, whichever)

this way threading will be more consistent between accounts

**Comment by compufox** [comment]
done! :3

**Comment by Lana-chan** [comment]
don't forget to push, fam

**Comment by compufox** [comment]
i gotchu :ok_hand:
