### ISSUE TITLE
empty toots with media don't crosspost

### ISSUE THREAD

**Issue by Lana-chan** [theZacAttacks/TwitPoster#4]
empty content tweets used to crash the crossposter because an empty tweet is invalid but that was before the crossposter was doing media too so now if you post media with no text the result is that toot doesn't get crossposted

**Comment by compufox** [comment]
hopefully fixed

gonna leave this open in case it isn't tho

**Comment by Lana-chan** [comment]
fixed by 6f5005cfd25bd4d5c77e60edcbe588cedb81b574
