### ISSUE TITLE
feature request: delete tweet if source toot was deleted

### ISSUE THREAD

**Issue by Lana-chan** [theZacAttacks/TwitPoster#5]
shouldn't be difficult since we have a list of toot<->tweet relations

**Comment by Lana-chan** [comment]
oh possibly boost -> retweet function too

**Comment by compufox** [comment]
how do you imagine the boosting functionality working?

i was thinking like sending the permalink of the original toot maybe?

**Comment by Lana-chan** [comment]
ah i mean if a toot that's currently tracked is boosted, then retweet the tweet that it's linked to

**Comment by compufox** [comment]
OH. okay! yeah that seems very doable :3

**Comment by Lana-chan** [comment]
can you imagine if we just made a server that hosted all of the mastodon->twitter status links

so that, if you interacted with another used on mastodon who was also using the crossposter, it would make tweets to mirror all interactions

soon you could use twitter without using twitter at all....

**Comment by Lana-chan** [comment]
Oh secondary request, status link list length settable in config, if you want to have more than 200

**Comment by compufox** [comment]
Deleting is done, as well as allowing the config to specify how many status ids to hold.

An issue with the boosting part. If you boost a *recent* post (like it's still on your timeline) it won't get picked up as a 'new' object by the streaming api. it has to be an older one. I'll look into it a bit more just to make SURE thats how it works, but for now im closing this!

**Comment by compufox** [comment]
testing the retweet functionality with what limitations we currently have

then ill push :3 (just letting you know)
