### ISSUE TITLE
Feature request: add option to disable crossposting replies to other users

### ISSUE THREAD

**Issue by joyeusenoelle** [theZacAttacks/TwitPoster#6]
It would be nice to have the option to disable crossposting replies to other users, so that Twitter never gets half a conversation. (I looked through the code and don't see this; if it's there, ignore me!) 

I believe this is as simple as checking `post.attributes['in_reply_to_account_id']` against the current poster's id.

**Comment by compufox** [comment]
It already checks and makes sure that any mastodon post that has a mention doesn't get cross posted ([link](https://github.com/theZacAttacks/TwitPoster/blob/8bf9c98b8496f8af74072872933747247ffacb8d/crossposter.rb#L175))

However, I know that some people use mobile clients that tag themselves for a selfreply. I'll look at this in a bit and make it more robust!

**Comment by joyeusenoelle** [comment]
I guess I missed that! Thank you!

**Comment by compufox** [comment]
Of course! :3
